services:
  # Node.js Application
  app:
    build:
        context: .
        dockerfile: Dockerfile
        target: base
    env_file:
        - .env-docker
    volumes:
        - ./:/usr/src/app
        - /usr/src/app/node_modules
    container_name: app
    ports:
        - '4000:4000'
    depends_on:
        - db
    environment:
        - CHOKIDAR_USEPOLLING=true
        - CHOKIDAR_INTERVAL=1000
    command: npm run dev

  # PostgreSQL Database
  db:
    image: postgres:latest
    ports:
      - "${PGPORT:-5432}:5432"
    restart: always
    env_file:
        - .env-docker
    environment:
      POSTGRES_DB: ${PGDATABASE:-minievs}
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD:-password}
    container_name: db
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/patients.csv:/data/patients.csv
      - ./data/eligibility.csv:/data/eligibility.csv
